apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-new-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/neo/Workplace/data"